name:                psst

version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- websockets
- random-string
- aeson
- bytestring
- unordered-containers

executables:
  psst-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
